### ISSUE TITLE
org.noo.pagination.interceptor.SQLHelp.java的getCount方法没有关闭链接

### ISSUE THREAD

**Issue by donilan** [fitzyyf/mybatis-pagination#3]
我是使用org.apache.commons.dbcp.BasicDataSource作为连接池的，当时我开了大概设置了8个链接为最大数量，当我访问有分页方法查询的页面大概7-8次左右就会出现不能获取链接的问题。

**Comment by fitzyyf** [comment]
能提供datasource的配置 我测试下么

**Comment by donilan** [comment]
&lt;bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource"
        destroy-method="close" p:driverClassName="${jdbc.driverClassName}"
        p:url="${jdbc.url}" p:username="${jdbc.username}" p:password="${jdbc.password}" />

就一份默认配置。 getCount方法里面没有关闭连接，好像不太对。

**Comment by jpuncle** [comment]
关键是这个方法，只关闭了rs和countStmt，没有关闭connection，加上就好了

```
public static int getCount() {
    try {
        // ...
    } finally {
        if (rs != null) {
            rs.close();
        }
        if (countStmt != null) {
            countStmt.close();
        }

        if (connection != null) {
            connection.close();
        }
    }
}
```

**Comment by fitzyyf** [comment]
## 现在的处理方式还是有些问题，Connection的获取不是从配置的datasource中获取，不是很好。目前新的版本已经修复了这个问题。

/**
- yfyang.poplar
- @author poplar.yfyang@iflytek
- @email: poplar1123@gmail.com 
- @cellphone: +86 18655121378
- @see yfyang@iflytek.com
- @blog yfyang.github.com 
  */
  ---------------------------------------------------------------------------

**Comment by fitzyyf** [comment]
具体的修复请看 [Plum-Mybatis](https://github.com/yfyang/plum/tree/master/src/main/java/plum/mybatis)

**Comment by fitzyyf** [comment]
Closed
