### ISSUE TITLE
PageContext.getPageContext() & PageContext.removeContext()

### ISSUE THREAD

**Issue by topvas7450** [fitzyyf/mybatis-pagination#4]
使用PageContext.getPageContext()產生分頁物件再查詢過一個table後是不是該清除此共用物件（ThreadLocal<PageContext>）
若此實在查詢其他table則分頁物件因page.getTotalRows()!=0便不會查詢totalrow
請問您使用PageContext.removeContext()的時機是在何時？？

**Comment by fitzyyf** [comment]
这里的`PageContext`的`ThreadLocal`只是为了保证其对象的单例，`removeContext`方法一般不会用到的。

**Comment by topvas7450** [comment]
目前我在使用PageContext.getPageContext()產生Pagination物件查詢a table
再用PageContext.getPageContext()產生Pagination物件查詢b table
在回頭查詢a table使用PageContext.getPageContext()產生Pagination物件所取得的totalRows會是a table的，
請問我有遺漏任何步驟嗎？

**Comment by fitzyyf** [comment]
你是外部显示的调用`PageContext`对象么。这个只是插件内部使用的一个方便管理`PageContext`对象的类啊。是用于拦截插件时获取信息的便利。外部使用，目前还未考虑这点

**Comment by topvas7450** [comment]
瞭解,原來是誤用
那請問外部使用Pagination實體要如何使用,不知是否有例子

List<BusinessObject> findAll(Pagination pagination)傳入Pagination實體
要取得分頁資訊必須到分頁實體才取的到嗎？？
傳入的Pagination實體似乎並沒有從PageContext.getPageContext()同步分頁資訊

@Paging(field="page1")
    public class BusinessObject{
        private RecordPage page1;

```
    //... get set ...
}
```

以上有些有些疑惑 謝謝
