### ISSUE TITLE
JDBC 连接泄露问题

### ISSUE THREAD

**Issue by akuma** [fitzyyf/mybatis-pagination#5]
PaginationInterceptor 类的第 65 行，从 datasource 中获取了一个连接用于执行 count 查询，
但发现用完之后并未进行关闭，这会导致连接泄露问题。

**Comment by fitzyyf** [comment]
我还是更新下这个问题。不过我还是建议用[plum-mybatis](https://github.com/yfyang/plum/tree/master/src/main/java/plum/mybatis)，这个的实现方式感觉过分实现了。
