### ISSUE TITLE
没人维护了吗？

### ISSUE THREAD

**Issue by ghost** [fitzyyf/mybatis-pagination#6]
看了下使用说明和源码，发现有点不对应。

**Comment by fitzyyf** [comment]
这个不打算继续下去了，我近期会将这个代码和文档同步。以后就在在[plum](https://github.com/yfyang/plum)中更新了。

**Comment by ghost** [comment]
好的，到时候看你的plum。

**Comment by ghost** [comment]
我试了下PaginationInterceptor这个拦截器，发现几个问题：
1、PageContext似乎少了set方法；
2、if (parameterObject != null && context == null) 第51行，context永远不可能等于null；
3、Object parameter = invocation.getArgs()[1];
     Object parameterObject = boundSql.getParameterObject();  parameter跟parameterObject是一样的。
4、传入多个查询参数没有支持。我改了下BaseInterceptor里的convertParameter方法，增加了一段代码：
if (parameterObject instanceof Page) {
            pageVO = (Pagination) parameterObject;
        }
        else if (parameterObject instanceof MapperMethod.MapperParamMap<?>) {
            @SuppressWarnings("unchecked")
            MapperMethod.MapperParamMap<Object> paramMap = (MapperMethod.MapperParamMap<Object>) parameterObject;
            // 如果多参数，分页参数要放到第一个位置
            parameterObject = paramMap.get("0");
            return convertParameter(parameterObject, pageVO);
        }

**Comment by fitzyyf** [comment]
恩 不错，后面我修改时注意下。
其实你可以fork一般版本进行修改。呵呵
这个很多细节都没有考虑好。主要是为了实现这个分页功能。
后来感觉分页功能其实没必要那么复杂，所以就放弃了。
